### ISSUE TITLE
LW005-MP Fport 8

### ISSUE THREAD

**Issue by chongzhang** [LoRaWAN-Product-Decoder/MOKOSMART-LoRaWAN-Product-Decoder#10]
https://github.com/LoRaWAN-Product-Decoder/MOKOSMART-LoRaWAN-Product-Decoder/blob/main/LW005-MP/LW005-MP%20on%20Chirstack.js#L53, should this value do the same `/ 3200` as L52?

**Comment by mokotechnology** [comment]
Yes, it should divid 3200 as well.

**Comment by mokotechnology** [comment]
Already updated
